github.com:
    users:
        etherbits:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: etherbits
